### ISSUE TITLE
New Feature: Pass in CSS file reference

### ISSUE THREAD

**Issue by RyanDurkin** [paceaux/selector-finder#1]
Is there anyway this could be extended to pass in a CSS file URL and it traverses all CSS selectors in the CSS file and tells you how many times each one is used?

**Comment by paceaux** [comment]
This is an excellent request. Now that there's some modicum of unit testing available, will begin work on this.

**Comment by paceaux** [comment]
@RyanDurkin , presently when the tool searches a page, the results look like this:

```
{
      "url": "https://blog.frankmtaylor.com/2012/04/26/learning-css-selectors-from-newbie-to-ninja/",
      "totalMatches": 7,
      "elements": [
        {
          "tag": "h2",
          "attributes": {
            "id": "site-description",
            "class": "site-description g-header__siteDescription",
            "itemprop": "description"
          }
        },
        {
          "tag": "h2",
          "attributes": {
            "class": "breadcrumbs__title"
          }
        },
```

If you're using a stylesheet, instead of a single selector, this of course means multiple selectors are being searched. Would your expectation be that each of these "results" also has the selector it matched against? Or would you want to see all the selectors that had matches in some array?

**Comment by RyanDurkin** [comment]
Hmmm... my request almost seems like it's an inverted version of this or possibly a different tool?

You'd pass in a css file reference, a sitemap reference and then the results would be something like this?

```
{
      "totalUnusedSelectors": 3,
      "selectors": [".heading",".hero-title",".primary-card"]
}
```

**Comment by paceaux** [comment]
Even better. That seems more achievable.

**Comment by RyanDurkin** [comment]
I don't think there's a need for the description, just the list of unused selectors

**Comment by paceaux** [comment]
as of right now, here's _roughly_ what the results would look like:
I'd originally built this to _find_ matches, not to filter out non-matches. But, your use-case makes total sense. So by default I'll leave descriptions _on_ for matches, and you'll have `unusedSelectors` for the ones that don't match. But I'll give a flag to turn off "match descriptions" in case _all_ you're interested in is the unused bit. 

```
{
      "url": "https://blog.frankmtaylor.com/2012/04/26/learning-css-selectors-from-newbie-to-ninja/",
      "elements": [
        {
          "tag": "h1",
          "attributes": {
            "id": "site-title",
            "class": "site-title g-header__siteTitle",
            "itemprop": "headline"
          },
          "selector": "h1"
        },
        {
          "tag": "h1",
          "attributes": {
            "class": "entry-title",
            "itemprop": "headline"
          },
          "selector": "h1"
        }
      ],
      "unusedSelectors": [
        ".foo",
        ".bar"
      ]
    },
```

**Comment by RyanDurkin** [comment]
Love it. This will be a huge help for projects you inherit or just some of your own personal projects that have grown out of control 😀

**Comment by paceaux** [comment]
Request complete. 

user now has `--cssFile` and `-f` for providing a file system path to a style sheet. Additionally, `--showElementDetails` and `-e` will collapse the details for element matches if the user is only interested in used and unused selectors for a given page.
