### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by RyanDurkin** [paceaux/selector-finder#3]
Does this tool only work against HTTPS URL's? I tried to run it against a local website xml sitemap that doesn't have an SSL certificate and I get:

```
Error: unable to verify the first certificate
    at TLSSocket.onConnectSecure (node:_tls_wrap:1508:34)
    at TLSSocket.emit (node:events:376:20)
    at TLSSocket._finishInit (node:_tls_wrap:942:8)
    at TLSWrap.ssl.onhandshakedone (node:_tls_wrap:716:12)
```

**Comment by paceaux** [comment]
i have had success with HTTPS urls in the past, but I'll test and see if I can reproduce the issue.

**Comment by paceaux** [comment]
I tested this on a local repo, using `localhost:9191`. I validated that my site was running in this _and_ that my sitemap had localhost urls. The utility ran fine. 

Could you share some additional details about the site? Can you give me a repo to look at, or a sample of the sitemap and a selector?

**Comment by RyanDurkin** [comment]
I think this is a problem with an SSL redirect on my local site as it works against another non-ssl website on the same server.

The local site is using a self signed certificate that it doesn't seem to like as it's not properly signed

**Comment by paceaux** [comment]
Ahh, ok. Then I'll close the issue.
